package com.ccumming.burp.controller;

enum ProgStatus {
  NOT_CONNECTED,
  CONNECTED,
  START_RECORDING_SENT,
  RECORDING_STARTED,
  HTTP_SENT,
  HTTP_RESPONSE_RECEIVED,
  STOP_RECORDING_SENT,
  RECORDING_STOPPED,
  TAINT_BYTES_SENT,
  TAINT_RESULTS_RECEIVED
}
